---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

app_test:
  DB_FILENAME: db/local/test.db
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

test:
  DB_FILENAME: db/local/test.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

production:
  # - assign DATABASE_URL in production
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: https://codepraise2022-api
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-production
  CLONE_QUEUE_URL: <set by AWS>