---
development:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>
  DB_FILENAME: db/local/dev.db

test:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>
  DB_FILENAME: db/local/test.db

production:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>