---
development:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>
  DB_FILENAME: <PATH/URL GOES HERE>

test:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>
  DB_FILENAME: <PATH/URL GOES HERE>

production:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>
  DATABASE_URL: <PATH/URL GOES HERE>